apiVersion: 1

contactPoints:
  - orgId: 1
    name: infra-discord
    receivers:
      - uid: infra-discord-receiver
        type: discord
        settings:
          url: $INFRA_ALERT_DISCORD_WEBHOOK_URL
          use_discord_username: true
          content: "[BridgeWork Infra Alert] {{ .CommonLabels.alertname }}"
        disableResolveMessage: false
